version: "3.7"

services:
  betterlife:
    container_name: bb
    image: bb
    build:
      context: ../../
      # context: ./ # 本配置文件放置在根路径下使用这一行, 然后注释上一行
      dockerfile: install/docker/Dockerfile
      target: betterlife
    working_dir: /var/www/html/betterlife
    ports:
      - 9000:9000
    volumes:
      - ../../:/var/www/html/betterlife
      # - ./:/var/www/html/betterlife # 本配置文件放置在根路径下使用这一行, 然后注释上一行
      - composer-data:/var/www/html/betterlife/install/vendor # 这一行的意思是容器里该文件夹不会被宿主机所覆盖
      - ueditor-data:/var/www/html/betterlife/misc/js/onlineditor/ueditor # 这一行的意思是容器里该文件夹不会被宿主机所覆盖

    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_DB: betterlife

  nginx:
    container_name: bb_nginx
    image: bb_nginx
    build:
      context: ../../
      # context: ./ # 本配置文件放置在根路径下使用这一行, 然后注释上一行
      dockerfile: install/docker/Dockerfile
      target: nginx
    working_dir: /var/www/html/betterlife
    depends_on:
      - betterlife
    ports:
      - 80:80
    volumes:
      - ../../:/var/www/html/betterlife
      # - ./:/var/www/html/betterlife # 本配置文件放置在根路径下使用这一行, 然后注释上一行
      - composer-data:/var/www/html/betterlife/install/vendor # 这一行的意思是容器里该文件夹不会被宿主机所覆盖
      - ueditor-data:/var/www/html/betterlife/misc/js/onlineditor/ueditor # 这一行的意思是容器里该文件夹不会被宿主机所覆盖

  mysql:
    image: mysql:5.7
    container_name: bb_mysql
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ../db/mysql:/docker-entrypoint-initdb.d/
      # - ./install/db/mysql:/docker-entrypoint-initdb.d/ # 本配置文件放置在根路径下使用这一行, 然后注释上一行
    environment: 
      MYSQL_DATABASE: betterlife
      MYSQL_ALLOW_EMPTY_PASSWORD: root
      MYSQL_ROOT_PASSWORD: 

  # redis:
  #   container_name: bb_redis
  #   image: redis:4.0.1
  #   command: redis-server --requirepass yourpassword
  #   ports:
  #       - 6379:6379

volumes:
  mysql-data:
  composer-data:
  ueditor-data: