version: "3.7"

services:
  betterlife:
    image: bb
    container_name: bb
    build:
      context: ../../
      dockerfile: install/docker/Dockerfile
      target: betterlife
    working_dir: /var/www/html/betterlife
    ports:
      - 9000:9000
    volumes:
      - ../../:/var/www/html/betterlife
      - composer-data:/var/www/html/betterlife/install/vendor # 这一行的意思是容器里该文件夹不会被宿主机所覆盖
      - ueditor-data:/var/www/html/betterlife/misc/js/onlineditor/ueditor # 这一行的意思是容器里该文件夹不会被宿主机所覆盖

    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_DB: betterlife
    restart: on-failure

  nginx:
    image: bb_nginx
    container_name: bb_nginx
    build:
      context: ../../
      dockerfile: install/docker/Dockerfile
      target: nginx
    working_dir: /var/www/html/betterlife
    depends_on:
      - betterlife
    ports:
      - 80:80
    volumes:
      - ../../:/var/www/html/betterlife
      - composer-data:/var/www/html/betterlife/install/vendor # 这一行的意思是容器里该文件夹不会被宿主机所覆盖
      - ueditor-data:/var/www/html/betterlife/misc/js/onlineditor/ueditor # 这一行的意思是容器里该文件夹不会被宿主机所覆盖
    environment:
      ENABLE_CRONTAB: "true"
    restart: on-failure

  mysql:
    image: mysql:5.7
    container_name: bb_mysql
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ../db/mysql:/docker-entrypoint-initdb.d/
    environment: 
      MYSQL_DATABASE: betterlife
      MYSQL_ALLOW_EMPTY_PASSWORD: root
      MYSQL_ROOT_PASSWORD: 
      TZ: Asia/Shanghai
    restart: on-failure

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:5.0.2
  #   container_name: bb_phpmyadmin
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - mysql
  #   environment:
  #     PMA_HOST: mysql
  #     TZ: Asia/Shanghai
  #   restart: on-failure

  # redis:
  #   image: redis:4.0.1
  #   # image: redis:6.2.6
  #   container_name: bb_redis
  #   command: redis-server --requirepass betterlife
  #   ports:
  #       - 6379:6379
  #   environment:
  #     TZ: Asia/Shanghai
  #   restart: on-failure

volumes:
  mysql-data:
  composer-data:
  ueditor-data:


# - 根路径下运行以下指令执行操作
# - 创建运行: docker-compose -f install/docker/docker-compose.yml up -d --build
# - 运行应用: docker-compose -f install/docker/docker-compose.yml start
# - 停止应用: docker-compose -f install/docker/docker-compose.yml stop
# - 进入应用: docker exec -it bb /bin/bash

# - 删除所有的容器: docker-compose -f install/docker/docker-compose.yml down
# - 删除生成的镜像: docker rmi bb_nginx bb mysql:5.7